version: "3"
services: 
  app:
    restart: always
    build: .
    container_name: node_test
    image: node_test
    depends_on:
      - mongo      
    command: npm start  
    volumes: 
      - './:/app'
    environment:
      - "PORT=3800"
    ports:
      - "3800:3800"
  mongo:
    container_name: mongo
    image: mongo:4
    volumes:
      - ./db:/data/db
    ports:
      - "27027:27017" 

